"use client";
import {useState,useEffect,FormEvent} from 'react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {Rotate3D,Wrench,Paintbrush,Check,MoveUpRight} from 'lucide-react';
import Model from './product-model';
export default function Home(){
const [open,setOpen]=useState(false),[color,setColor]=useState('gray'),[size,setSize]=useState('1200 × 300 мм'),[method,setMethod]=useState('Звонок'),[status,setStatus]=useState(''),[busy,setBusy]=useState(false),[photo,setPhoto]=useState('');
useEffect(()=>{const context=(document as any).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();Promise.resolve(context.registerTool({name:'open_request_form',description:'Открывает форму заявки, без отправки.',inputSchema:{type:'object',properties:{},additionalProperties:false},execute:(input:any)=>{if(!input||typeof input!=='object'||Array.isArray(input)||Object.keys(input).length)throw new Error('Ожидается пустой объект');setOpen(true);return {opened:true};}},{signal:lifecycle.signal})).catch(()=>{});return()=>lifecycle.abort();},[]);
async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget;setBusy(true);setStatus('');try{const r=await fetch('/api/request',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...Object.fromEntries(new FormData(form)),size,color:color==='gray'?'Серый':'Чёрный',method})});const result=await r.json() as {message:string};setStatus(result.message);if(r.ok)form.reset();}catch{setStatus('Не удалось отправить. Попробуйте ещё раз или напишите Сергею в Telegram.');}finally{setBusy(false);}}
return <><header className="nav"><a className="brand" href="#"><b>К</b><span>КАНТОВАТЕЛЬ<small>ВЕЛИКИЙ НОВГОРОД</small></span></a><nav><a href="#about">Конструкция</a><a href="#photos">В работе</a><a href="#order">Комплектация</a></nav><button className="nav-request" onClick={()=>setOpen(true)}>Оставить заявку</button></header><main>
<section className="cinema-hero"><div className="cinema-shade"/><div className="cinema-copy"><h1>Кантователь<br/>для садового трактора</h1><p>Для очистки деки, замены ножей<br/>и обслуживания райдера</p><div className="cinema-action"><span>С доставкой <span className="nowrap">19 000 ₽</span></span><button className="primary" onClick={()=>setOpen(true)}>Оставить заявку</button></div></div><div className="cinema-foot"><span>Изготовлено в Великом Новгороде</span><a href="#explore">Посмотреть конструкцию</a><span>Доставка СДЭК по России</span></div></section>
<section className="model-section wrap" id="explore"><div className="model-intro"><h2>Конструкция</h2><p>Стальная рама с ручной лебёдкой и колёсами для перемещения</p><a className="ghost" href="#order">Размеры и комплектация</a></div><div className="hero-product"><div className="model-label"><span>3D-МОДЕЛЬ</span><span>ОБЗОР 360°</span></div><Model color={color}/><div className="model-bottom"><span><Rotate3D size={18}/>Поверните модель</span><div className="swatches"><button aria-label="Серый цвет" aria-pressed={color==='gray'} className="swatch gray" onClick={()=>setColor('gray')}/><button aria-label="Чёрный цвет" aria-pressed={color==='black'} className="swatch black" onClick={()=>setColor('black')}/><span>{color==='gray'?'Серый':'Чёрный'}</span></div></div><p className="model-note">Модель по фотографиям — детали уточним при заказе</p></div></section><div className="spec-strip wrap"><div><span>РАЗМЕРЫ</span><strong>1200 / 1300 × 300 мм</strong></div><div><span>ПОКРЫТИЕ</span><strong>Порошковая окраска</strong></div><div><span>ПОД ЗАКАЗ</span><strong>Индивидуальные размеры</strong></div></div>
<section className="section wrap" id="about"><div className="section-head"><h2>Доступ к деке<br/>и ножам</h2><p>Кантователь наклоняет райдер набок, чтобы можно было убрать траву с деки и обслужить ножи</p></div><div className="feature-grid"><div className="work-photo"><img src="/images/work.png" alt="Кантователь поднимает райдер: доступ к деке и ножам" loading="lazy"/><span>Очистка деки</span></div><div className="feature-list">{[[Wrench,'Очистка и обслуживание','Для удаления травы, замены ножей и мелкого ремонта'],[Rotate3D,'Ручная лебёдка','Подъём вращением рукоятки, без подключения к электричеству'],[Paintbrush,'Порошковая окраска','Чёрный и серый в стандартном исполнении, другие цвета под заказ']].map(([Icon,title,desc]:any)=><article key={title}><Icon/><div><h3>{title}</h3><p>{desc}</p></div></article>)}</div></div></section>
<section className="section wrap" id="photos"><div className="gallery-heading"><div><h2>Фото в работе</h2></div></div><div className="gallery">{[['caiman.jpg','Caiman','Жёлтая окраска'],['yardfox.jpg','Yard Fox','Индивидуальный цвет'],['stihl.jpg','STIHL','Обслуживание в гараже']].map(([src,title,desc])=><button className="photo-card" key={src} onClick={()=>setPhoto(src)}><div><img src={'/images/'+src} alt={'Кантователь с райдером '+title} loading="lazy"/><span><MoveUpRight size={18}/></span></div><h3>{title}</h3><p>{desc}</p></button>)}</div><p className="small">Размер подберём по модели вашего райдера</p></section>
<section className="section wrap" id="order"><div className="order-panel"><div><h2>Что входит<br/>в комплект</h2><p>Металлическая конструкция, ручная лебёдка,<br/>колёса, крепёж и порошковая окраска</p><ul>{['Размеры 1200 × 300 или 1300 × 300 мм','Изготовление под ваш райдер','Доставка СДЭК включена в стоимость'].map(t=><li key={t}><Check size={17}/>{t}</li>)}</ul></div><div className="order-choice"><span className="small">КОМПЛЕКТ С ДОСТАВКОЙ</span><div className="big-price">19 000 <span>₽</span></div><label>Размер</label><Select value={size} onValueChange={setSize}><SelectTrigger className="size-select"><SelectValue/></SelectTrigger><SelectContent>{['1200 × 300 мм','1300 × 300 мм','Индивидуальный размер'].map(s=><SelectItem key={s} value={s}>{s}</SelectItem>)}</SelectContent></Select><button className="primary" onClick={()=>setOpen(true)}>Оставить заявку</button><p className="small">Доставка включена в цену / Нестандартный размер и цвет рассчитаем отдельно</p></div></div></section>
<section className="contact wrap"><div><h2>Связаться с Сергеем</h2><p>Пришлите марку и модель райдера<br/>для подбора размера и расчёта заказа</p></div><div className="contact-links"><a className="contact-phone" href="tel:+79062036089">+7 906 203-60-89</a><div><a className="ghost" href="https://t.me/meqa921" target="_blank" rel="noreferrer">Telegram</a><a className="ghost" href="https://vk.ru/sergey_yakovlev76" target="_blank" rel="noreferrer">ВКонтакте</a></div><span className="small">Великий Новгород</span></div></section></main><footer className="wrap"><span>КАНТОВАТЕЛЬ</span><span>© 2026</span></footer>
<Dialog open={open} onOpenChange={setOpen}><DialogContent className="request-modal"><DialogTitle className="modal-title">Оставить заявку</DialogTitle><DialogDescription>Сергей свяжется с вами по заказу</DialogDescription><form onSubmit={submit}><div className="form-row"><label>Ваше имя<input name="name" required maxLength={80} autoComplete="given-name" placeholder="Как к вам обращаться"/></label><label>Телефон<input name="phone" required type="tel" minLength={10} maxLength={25} autoComplete="tel" placeholder="+7 999 123-45-67"/></label></div><label>Соцсеть или @ник <small>необязательно</small><input name="social" maxLength={180} placeholder="Telegram, ВКонтакте или ссылка"/></label><label>Как удобнее связаться</label><Select value={method} onValueChange={setMethod}><SelectTrigger className="size-select"><SelectValue/></SelectTrigger><SelectContent>{['Звонок','Telegram','ВКонтакте'].map(m=><SelectItem key={m} value={m}>{m}</SelectItem>)}</SelectContent></Select><label>Модель райдера <small>необязательно</small><input name="rider" maxLength={120} placeholder="Марка и модель вашей техники"/></label><label>Комментарий <small>необязательно</small><textarea name="comment" maxLength={1500} rows={2} placeholder="Пожелания по размеру или цвету"/></label><input className="honeypot" name="website" tabIndex={-1} autoComplete="off" aria-hidden="true"/><p className="small">{size} / {color==='gray'?'Серый':'Чёрный'}</p><p className="small">Нажимая «Отправить заявку», вы соглашаетесь передать указанные данные Сергею через Telegram для связи по этому заказу.</p><button className="primary submit" disabled={busy}>{busy?'Отправляем…':'Отправить заявку'}</button>{status&&<p role="status" className="form-status">{status} <a href="https://t.me/meqa921">Telegram Сергея</a></p>}</form></DialogContent></Dialog>
<Dialog open={!!photo} onOpenChange={v=>!v&&setPhoto('')}><DialogContent className="photo-modal"><DialogTitle className="sr-only">Кантователь в работе</DialogTitle><DialogDescription className="sr-only">Фотография изделия</DialogDescription>{photo&&<img src={'/images/'+photo} alt="Кантователь в работе"/>}</DialogContent></Dialog></>;
}





